# -*-python-*-
Import("env")

env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])


# Export/Import Symbols for windows
if env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    env.AppendUnique(LINKFLAGS=LINKFLAGS)


# Select and install the headers


includes = env.ALEAGlob("*.h")
includes += env.ALEAGlob("*.hpp")

env.ALEAIncludes("tree_statistic", includes)


my_debug = True

if env['debug']:
    env.Append(CPPDEFINES= ['DEBUG'])

if my_debug:   
    env.AppendUnique(LIBS=['efence'])
    CPPFLAGS=["-g"]
    env.AppendUnique(CPPFLAGS=CPPFLAGS)
    if '-DNDEBUG' in env._dict['CCFLAGS']:
        env._dict['CCFLAGS'] = []
    if '-DNDEBUG' in env._dict['CXXFLAGS']:
        env._dict['CXXFLAGS'] = []
    # print env._dict
    

# Uncomment if needed
# CPPFLAGS=["-g"]
# env.AppendUnique(CPPFLAGS=CPPFLAGS)

# optional

# env.AppendUnique(LIBS=['eigen2'])

# Build shared libraries

#sources = env.ALEAGlob("*.cpp")

sources= Split("""
base_int_fl_containers.cpp
int_fl_containers.cpp
generic_tree.cpp
generic_typed_edge_tree.cpp
int_trees.cpp
typed_edge_trees.cpp
tree_labels.cpp
multivariate_distribution.cpp
multivariate_distribution_algorithm.cpp
mv_histogram_tools.cpp
univariate_conditional_distribution.cpp
multivariate_conditional_distribution.cpp
hidden_markov_tree.cpp
hidden_markov_ind_out_tree.cpp
hmt_algorithms.cpp
markov_out_tree.cpp
mot_algorithms.cpp
""")


# Build the library
lib = env.ALEALibrary("vptree_statistic", sources)

